from django.urls import path

from .views import (  # SendPhoneOTPView,; VerifyPhoneOTPView,
    AdminApproveRejectUserView,
    AdminDashboardStatsView,
    AdminListUsersView,
    AdminOTPVerifyView,
    AdminPendingBrokerListView,
    AdminPendingSellerListView,
    AdminPropertyListView,
    AdminTogglePropertyStatusView,
    AdminToggleUserStatusView,
    BrokerOTPVerifyView,
    ChangePasswordView,
    LoginView,
    LogoutView,
    ProfileView,
    RefreshTokenView,
    RegisterView,
    ResetPasswordConfirmView,
    ResetPasswordRequestView,
    SaveFCMTokenView,
)
from .views_google import GoogleLoginView
from .views_email_otp import SendEmailOTPView,VerifyEmailOTPView
urlpatterns = [
    path("register/", RegisterView.as_view()),
    path("login/", LoginView.as_view()),
    path("profile/", ProfileView.as_view()),
    path("logout/", LogoutView.as_view()),
    path("change-password/", ChangePasswordView.as_view()),
    path("reset-password/request/", ResetPasswordRequestView.as_view()),
    path("reset-password/confirm/", ResetPasswordConfirmView.as_view()),
    path("admin/verify-otp/", AdminOTPVerifyView.as_view()),
    path("refresh/", RefreshTokenView.as_view()),
    path("save-fcm-token/", SaveFCMTokenView.as_view()),
    path("google-login/", GoogleLoginView.as_view()),
    path("broker/verify-otp/", BrokerOTPVerifyView.as_view()),
    path("admin/users/", AdminListUsersView.as_view(), name="admin-users"),
    path(
        "admin/users/<int:user_id>/toggle-status/",
        AdminToggleUserStatusView.as_view(),
        name="toggle-user-status",
    ),
    path("admin/stats/", AdminDashboardStatsView.as_view(), name="admin-stats"),
    path("admin/properties/", AdminPropertyListView.as_view(), name="admin-properties"),
    path(
        "admin/properties/<int:property_id>/toggle-status/",
        AdminTogglePropertyStatusView.as_view(),
        name="toggle-property-status",
    ),
    path("admin/pending/sellers/", AdminPendingSellerListView.as_view()),
    path("admin/pending/brokers/", AdminPendingBrokerListView.as_view()),
    path(
        "admin/approve-reject/<int:user_id>/",
        AdminApproveRejectUserView.as_view(),
        name="admin-approve-reject",
    ),
    path("email/send-otp/", SendEmailOTPView.as_view()),
    path("email/verify-otp/", VerifyEmailOTPView.as_view()),
]
