# Generated by Django 5.2.9 on 2025-12-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("plot", "Plot"),
                            ("house", "House"),
                            ("flat", "Flat"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_negotiable", models.BooleanField(default=True)),
                ("area_size", models.FloatField(help_text="Area size value")),
                (
                    "area_unit",
                    models.CharField(
                        choices=[("sqft", "Sqft"), ("cent", "Cent")],
                        default="sqft",
                        max_length=10,
                    ),
                ),
                (
                    "property_age_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many years the property has been used",
                        null=True,
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_renovated_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ownership_count", models.PositiveIntegerField(default=1)),
                (
                    "reason_for_selling",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "nearby_places",
                    models.JSONField(
                        blank=True,
                        help_text="schools, hospitals, bus stand, metro, etc.",
                        null=True,
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("parking_available", models.BooleanField(default=False)),
                (
                    "furnishing_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("facing", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("sold", "Sold"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("interest_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
