# Generated by Django 5.2.9 on 2025-12-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_adminloginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
