# Generated by Django 5.2.9 on 2025-12-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_phoneotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneOTP",
        ),
    ]
