# Generated by Django 5.2.9 on 2026-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_phoneotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
