# Generated by Django 5.2.9 on 2026-01-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_brokerloginotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneOTP",
        ),
    ]
